#!/bin/sh
# Generated by nix/openstarbound.nix.
#
# The Nix store is read-only, so the boot configuration Starbound expects next
# to the binary (assetDirectories / storageDirectory / logDirectory) cannot be
# kept there.  This launcher materialises it under the user's runtime
# directory, then execs the real binary from $out/libexec.
#
# Overrides (all optional):
#   OPENSTARBOUND_RUNTIME_DIR  default: $XDG_DATA_HOME/openstarbound
#   OPENSTARBOUND_ASSETS       default: $OPENSTARBOUND_RUNTIME_DIR/assets
#   OPENSTARBOUND_MODS         default: $OPENSTARBOUND_RUNTIME_DIR/mods
#   OPENSTARBOUND_STORAGE      default: $OPENSTARBOUND_RUNTIME_DIR/storage
#   OPENSTARBOUND_LOGS         default: $OPENSTARBOUND_RUNTIME_DIR/logs
# Passing an explicit `-bootconfig` bypasses all of the above.  Note that the
# game's option parser only accepts single-dash long options.
set -eu

runtime_dir="${OPENSTARBOUND_RUNTIME_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/openstarbound}"
assets_dir="${OPENSTARBOUND_ASSETS:-$runtime_dir/assets}"
mods_dir="${OPENSTARBOUND_MODS:-$runtime_dir/mods}"
storage_dir="${OPENSTARBOUND_STORAGE:-$runtime_dir/storage}"
logs_dir="${OPENSTARBOUND_LOGS:-$runtime_dir/logs}"

for arg in "$@"; do
  case "$arg" in
  -bootconfig | -bootconfig=* | --bootconfig | --bootconfig=*)
    exec "@binary@" "$@"
    ;;
  esac
done

mkdir -p "$runtime_dir" "$assets_dir" "$mods_dir" "$storage_dir" "$logs_dir"

found_pak=""
for pak in "$assets_dir"/*.pak; do
  [ -e "$pak" ] && found_pak=1
done
if [ -z "$found_pak" ]; then
  echo "openstarbound: no .pak in $assets_dir" >&2
  echo "openstarbound: Starbound's own assets are required, e.g." >&2
  echo "openstarbound:   ln -s /path/to/Starbound/assets/packed.pak $assets_dir/" >&2
fi

boot_config="$runtime_dir/sbinit.config"
tmp_config="$boot_config.tmp.$$"
trap 'rm -f "$tmp_config"' EXIT INT TERM
cat > "$tmp_config" <<EOF
{
  "assetDirectories": ["@bundledAssets@", "$assets_dir", "$mods_dir"],
  "storageDirectory": "$storage_dir",
  "logDirectory": "$logs_dir"
}
EOF
mv -f "$tmp_config" "$boot_config"
trap - EXIT INT TERM

exec "@binary@" -bootconfig "$boot_config" "$@"
