#!/bin/sh
# Generated by nix/openstarbound.nix — runs the packaged game_tests against a
# local copy of Starbound's assets and records a report.
#
# game_tests cannot run as part of the build: Starbound's own assets are not
# redistributable, so they are gitignored and therefore not part of the flake
# source.  This launcher takes them from the local filesystem at run time.
#
#   assets : $OPENSTARBOUND_ASSETS (default $XDG_DATA_HOME/openstarbound/assets)
#            packed.pak is used when present, otherwise the whole directory
#   report : $OPENSTARBOUND_TEST_OUT (default ./game-tests-report)
#   timeout: $OPENSTARBOUND_TEST_TIMEOUT seconds per test run (default 120,
#            0 disables the timeout)
#
# Without arguments every test case runs in its own process with its own
# timeout, so one stuck case cannot hide the rest.  With arguments a single run
# is made and the arguments are handed to game_tests unchanged, e.g.
#   nix run .#game-tests -- --gtest_filter=WeatherTest.*
set -eu

assets_dir="${OPENSTARBOUND_ASSETS:-${XDG_DATA_HOME:-$HOME/.local/share}/openstarbound/assets}"
out_dir="${OPENSTARBOUND_TEST_OUT:-$PWD/game-tests-report}"
timeout_secs="${OPENSTARBOUND_TEST_TIMEOUT:-120}"

vanilla=""
if [ -f "$assets_dir/packed.pak" ]; then
  vanilla="$assets_dir/packed.pak"
elif [ -d "$assets_dir" ]; then
  vanilla="$assets_dir"
fi
if [ -z "$vanilla" ]; then
  echo "openstarbound: no Starbound assets in $assets_dir" >&2
  echo "openstarbound: point OPENSTARBOUND_ASSETS at a Starbound assets directory, e.g." >&2
  echo "openstarbound:   OPENSTARBOUND_ASSETS=/path/to/Starbound/assets nix run .#game-tests" >&2
  exit 2
fi

mkdir -p "$out_dir/storage" "$out_dir/logs" "$out_dir/cases"
boot_config="$out_dir/sbinit.config"
cat > "$boot_config" <<EOF
{
  "assetSources": ["$vanilla", "@bundledAssets@/opensb"],
  "storageDirectory": "$out_dir/storage",
  "logDirectory": "$out_dir/logs"
}
EOF

asset_identity="$vanilla"
if [ -f "$vanilla" ]; then
  asset_identity="$vanilla ($(sha256sum "$vanilla" | cut -c1-16)…)"
fi
# Captured here: the summary writer must not see its own arguments.
if [ $# -gt 0 ]; then
  header_arguments="$*"
else
  header_arguments="<all cases, one process each>"
fi

echo "openstarbound: game_tests"
echo "  assets : $asset_identity"
echo "  report : $out_dir"
echo "  timeout: ${timeout_secs}s per run"

write_summary() {
  {
    echo "assets: $asset_identity"
    echo "arguments: $header_arguments"
    echo "timeout: ${timeout_secs}s"
    echo "exit status: $1"
    echo
    shift
    cat "$@"
  } > "$out_dir/summary.txt"
}

if [ $# -gt 0 ]; then
  # Single run with the caller's arguments, output streamed.
  rm -f "$out_dir/game-tests.json"
  # The braces run in a subshell that inherits the shell options, so -e has to
  # be off: a failing run must record its status instead of aborting here.
  set +e
  if [ "$timeout_secs" = 0 ]; then
    { "@gameTests@" -bootconfig "$boot_config" "--gtest_output=json:$out_dir/game-tests.json" "$@"; echo $? > "$out_dir/exit-status"; } 2>&1 | tee "$out_dir/game-tests.log"
  else
    { timeout "$timeout_secs" "@gameTests@" -bootconfig "$boot_config" "--gtest_output=json:$out_dir/game-tests.json" "$@"; echo $? > "$out_dir/exit-status"; } 2>&1 | tee "$out_dir/game-tests.log"
  fi
  set -e

  status="$(cat "$out_dir/exit-status")"
  if [ "$status" = 124 ]; then
    echo "openstarbound: stopped after ${timeout_secs}s" >&2
  fi
  sed -n '/^\[  PASSED  \]/,$p' "$out_dir/game-tests.log" > "$out_dir/summary.body" || true
  write_summary "$status" "$out_dir/summary.body"
  rm -f "$out_dir/summary.body"
  echo "openstarbound: summary in $out_dir/summary.txt"
  cat "$out_dir/summary.txt"
  exit "$status"
fi

# Sweep: one process per test case, so a hang is recorded instead of aborting
# the whole suite.
"@gameTests@" --gtest_list_tests -bootconfig "$boot_config" 2> /dev/null \
  | awk '/^[^[:space:]].*\.$/ { suite = $1 } /^[[:space:]][[:space:]][^[:space:]]+$/ { print suite $1 }' \
  > "$out_dir/cases.list"

cases_file="$out_dir/cases.txt"
printf '%-46s %s\n' "case" "result" > "$cases_file"
pass=0
failed=0

while read -r case_name; do
  case_log="$out_dir/cases/$case_name.log"
  case_json="$out_dir/cases/$case_name.json"
  rm -f "$case_json"
  set +e
  if [ "$timeout_secs" = 0 ]; then
    "@gameTests@" -bootconfig "$boot_config" "--gtest_filter=$case_name" "--gtest_output=json:$case_json" > "$case_log" 2>&1
  else
    timeout "$timeout_secs" "@gameTests@" -bootconfig "$boot_config" "--gtest_filter=$case_name" "--gtest_output=json:$case_json" > "$case_log" 2>&1
  fi
  case_status=$?
  set -e

  case "$case_status" in
  0)
    verdict="pass"
    pass=$((pass + 1))
    ;;
  124)
    verdict="timeout (${timeout_secs}s)"
    failed=$((failed + 1))
    ;;
  *)
    verdict="fail (exit $case_status)"
    failed=$((failed + 1))
    ;;
  esac
  printf '%-46s %s\n' "$case_name" "$verdict" | tee -a "$cases_file"
done < "$out_dir/cases.list"

if [ "$failed" -eq 0 ]; then
  status=0
else
  status=1
fi
{
  echo "cases: $((pass + failed)), passed: $pass, not passed: $failed"
  echo
  cat "$cases_file"
} > "$out_dir/summary.body"
write_summary "$status" "$out_dir/summary.body"
rm -f "$out_dir/summary.body"
echo "openstarbound: summary in $out_dir/summary.txt"
cat "$out_dir/summary.txt"
exit "$status"
