set (star_game_HEADERS
    StarActorMovementController.hpp
    StarAiTypes.hpp
    StarArmorWearer.hpp
    StarBehaviorState.hpp
    StarBiome.hpp
    StarBiomePlacement.hpp
    StarCelestialCoordinate.hpp
    StarCelestialGraphics.hpp
    StarCelestialParameters.hpp
    StarCelestialTypes.hpp
    StarChatAction.hpp
    StarChatProcessor.hpp
    StarChatTypes.hpp
    StarClientContext.hpp
    StarCodex.hpp
    StarCollisionBlock.hpp
    StarCollisionGenerator.hpp
    StarCommandProcessor.hpp
    StarDamage.hpp
    StarDamageManager.hpp
    StarDamageTypes.hpp
    StarDrawable.hpp
    StarDungeonGenerator.hpp
    StarEffectEmitter.hpp
    StarEntityFactory.hpp
    StarEntityMap.hpp
    StarEntityRendering.hpp
    StarEntityRenderingTypes.hpp
    StarEntitySplash.hpp
    StarFallingBlocksAgent.hpp
    StarForceRegions.hpp
    StarGameTimers.hpp
    StarGameTypes.hpp
    StarHumanoid.hpp
    StarInput.hpp
    StarInteractionTypes.hpp
    StarInterpolationTracker.hpp
    StarInventoryTypes.hpp
    StarItem.hpp
    StarItemBag.hpp
    StarItemDescriptor.hpp
    StarItemDrop.hpp
    StarItemRecipe.hpp
    StarLightSource.hpp
    StarLiquidTypes.hpp
    StarMaterialRenderProfile.hpp
    StarMaterialTypes.hpp
    StarMonster.hpp
    StarMovementController.hpp
    StarNetPackets.hpp
    StarNetPacketSocket.hpp
    StarNetworkedAnimator.hpp
    StarNpc.hpp
    StarObject.hpp
    StarParallax.hpp
    StarParticle.hpp
    StarParticleManager.hpp
    StarPlant.hpp
    StarPlantDrop.hpp
    StarPlatformerAStar.hpp
    StarPlatformerAStarTypes.hpp
    StarPlayer.hpp
    StarPlayerBlueprints.hpp
    StarPlayerCodexes.hpp
    StarPlayerCompanions.hpp
    StarPlayerDeployment.hpp
    StarPlayerFactory.hpp
    StarPlayerInventory.hpp
    StarPlayerLog.hpp
    StarPlayerStorage.hpp
    StarPlayerTech.hpp
    StarPlayerTypes.hpp
    StarPlayerUniverseMap.hpp
    StarProjectile.hpp
    StarQuestDescriptor.hpp
    StarQuestManager.hpp
    StarQuests.hpp
    StarRoot.hpp
    StarRootLoader.hpp
    StarServerClientContext.hpp
    StarSky.hpp
    StarSkyParameters.hpp
    StarSkyRenderData.hpp
    StarSkyTypes.hpp
    StarSongbook.hpp
    StarSpawner.hpp
    StarStagehand.hpp
    StarStatistics.hpp
    StarStatusController.hpp
    StarStatusTypes.hpp
    StarSystemWorld.hpp
    StarSystemWorldClient.hpp
    StarSystemWorldServer.hpp
    StarSystemWorldServerThread.hpp
    StarTeamClient.hpp
    StarTeamManager.hpp
    StarTechController.hpp
    StarTileDamage.hpp
    StarTileDrawer.hpp
    StarTileModification.hpp
    StarTileSectorArray.hpp
    StarToolUser.hpp
    StarUniverseClient.hpp
    StarUniverseConnection.hpp
    StarUniverseServer.hpp
    StarUniverseSettings.hpp
    StarVehicle.hpp
    StarWarping.hpp
    StarWeather.hpp
    StarWeatherTypes.hpp
    StarWireProcessor.hpp
    StarWiring.hpp
    StarWorldCamera.hpp
    StarWorldClient.hpp
    StarWorldClientThread.hpp
    StarWorldClientState.hpp
    StarWorldImpl.hpp
    StarWorldLayout.hpp
    StarWorldParameters.hpp
    StarWorldRenderData.hpp
    StarWorldServer.hpp
    StarWorldServerThread.hpp
    StarWorldStorage.hpp
    StarWorldStructure.hpp
    StarWorldTemplate.hpp
    StarWorldTiles.hpp

    interfaces/StarActorEntity.hpp
    interfaces/StarAnchorableEntity.hpp
    interfaces/StarActivatableItem.hpp
    interfaces/StarAggressiveEntity.hpp
    interfaces/StarBeamItem.hpp
    interfaces/StarChattyEntity.hpp
    interfaces/StarContainerEntity.hpp
    interfaces/StarDamageBarEntity.hpp
    interfaces/StarDurabilityItem.hpp
    interfaces/StarEffectSourceItem.hpp
    interfaces/StarEmoteEntity.hpp
    interfaces/StarEntity.hpp
    interfaces/StarFireableItem.hpp
    interfaces/StarInteractiveEntity.hpp
    interfaces/StarLoungingEntities.hpp
    interfaces/StarMobileEntity.hpp
    interfaces/StarNametagEntity.hpp
    interfaces/StarNonRotatedDrawablesItem.hpp
    interfaces/StarPhysicsEntity.hpp
    interfaces/StarPreviewTileTool.hpp
    interfaces/StarPointableItem.hpp
    interfaces/StarPortraitEntity.hpp
    interfaces/StarPreviewableItem.hpp
    interfaces/StarRenderableItem.hpp
    interfaces/StarScriptedEntity.hpp
    interfaces/StarStatusEffectEntity.hpp
    interfaces/StarStatusEffectItem.hpp
    interfaces/StarSwingableItem.hpp
    interfaces/StarTileEntity.hpp
    interfaces/StarToolUserEntity.hpp
    interfaces/StarToolUserItem.hpp
    interfaces/StarWarpTargetEntity.hpp
    interfaces/StarWireEntity.hpp
    interfaces/StarWorld.hpp
    interfaces/StarUniverse.hpp

    items/StarArmors.hpp
    items/StarAugmentItem.hpp
    items/StarTools.hpp

    objects/StarContainerObject.hpp

    scripting/StarLuaActorMovementComponent.hpp
    scripting/StarLuaAnimationComponent.hpp
    scripting/StarLuaGameConverters.hpp
    scripting/StarLuaComponents.hpp
    scripting/StarLuaRoot.hpp
    scripting/StarScriptableThread.hpp
  )

set (star_game_SOURCES
    StarActorMovementController.cpp
    StarAiTypes.cpp
    StarArmorWearer.cpp
    StarBehaviorState.cpp
    StarBiome.cpp
    StarBiomePlacement.cpp
    StarCelestialCoordinate.cpp
    StarCelestialGraphics.cpp
    StarCelestialParameters.cpp
    StarCelestialTypes.cpp
    StarChatAction.cpp
    StarChatProcessor.cpp
    StarChatTypes.cpp
    StarClientContext.cpp
    StarCodex.cpp
    StarCollisionBlock.cpp
    StarCollisionGenerator.cpp
    StarCommandProcessor.cpp
    StarDamage.cpp
    StarDamageManager.cpp
    StarDamageTypes.cpp
    StarDrawable.cpp
    StarDungeonGenerator.cpp
    StarEffectEmitter.cpp
    StarEntityFactory.cpp
    StarEntityMap.cpp
    StarEntityRendering.cpp
    StarEntityRenderingTypes.cpp
    StarEntitySplash.cpp
    StarFallingBlocksAgent.cpp
    StarForceRegions.cpp
    StarGameTimers.cpp
    StarGameTypes.cpp
    StarHumanoid.cpp
    StarInput.cpp
    StarInteractionTypes.cpp
    StarInterpolationTracker.cpp
    StarInventoryTypes.cpp
    StarItem.cpp
    StarItemBag.cpp
    StarItemDescriptor.cpp
    StarItemDrop.cpp
    StarItemRecipe.cpp
    StarLightSource.cpp
    StarLiquidTypes.cpp
    StarMaterialRenderProfile.cpp
    StarMonster.cpp
    StarMovementController.cpp
    StarNetPackets.cpp
    StarNetPacketSocket.cpp
    StarNetworkedAnimator.cpp
    StarNpc.cpp
    StarObject.cpp
    StarParallax.cpp
    StarParticle.cpp
    StarParticleManager.cpp
    StarPlant.cpp
    StarPlantDrop.cpp
    StarPlatformerAStar.cpp
    StarPlatformerAStarTypes.cpp
    StarPlayer.cpp
    StarPlayerBlueprints.cpp
    StarPlayerCodexes.cpp
    StarPlayerCompanions.cpp
    StarPlayerDeployment.cpp
    StarPlayerFactory.cpp
    StarPlayerInventory.cpp
    StarPlayerLog.cpp
    StarPlayerStorage.cpp
    StarPlayerTech.cpp
    StarPlayerTypes.cpp
    StarPlayerUniverseMap.cpp
    StarProjectile.cpp
    StarQuestDescriptor.cpp
    StarQuestManager.cpp
    StarQuests.cpp
    StarRoot.cpp
    StarRootLoader.cpp
    StarServerClientContext.cpp
    StarSky.cpp
    StarSkyParameters.cpp
    StarSkyRenderData.cpp
    StarSkyTypes.cpp
    StarSongbook.cpp
    StarSpawner.cpp
    StarStagehand.cpp
    StarStatistics.cpp
    StarStatusController.cpp
    StarStatusTypes.cpp
    StarSystemWorld.cpp
    StarSystemWorldClient.cpp
    StarSystemWorldServer.cpp
    StarSystemWorldServerThread.cpp
    StarTeamClient.cpp
    StarTeamManager.cpp
    StarTechController.cpp
    StarTileDamage.cpp
    StarTileDrawer.cpp
    StarTileModification.cpp
    StarToolUser.cpp
    StarUniverseClient.cpp
    StarUniverseConnection.cpp
    StarUniverseServer.cpp
    StarUniverseSettings.cpp
    StarVehicle.cpp
    StarWarping.cpp
    StarWeather.cpp
    StarWeatherTypes.cpp
    StarWireProcessor.cpp
    StarWiring.cpp
    StarWorldCamera.cpp
    StarWorldClient.cpp
    StarWorldClientThread.cpp
    StarWorldClientState.cpp
    StarWorldLayout.cpp
    StarWorldParameters.cpp
    StarWorldServer.cpp
    StarWorldServerThread.cpp
    StarWorldStorage.cpp
    StarWorldStructure.cpp
    StarWorldTemplate.cpp
    StarWorldTiles.cpp

    interfaces/StarAnchorableEntity.cpp
    interfaces/StarBeamItem.cpp
    interfaces/StarContainerEntity.cpp
    interfaces/StarDamageBarEntity.cpp
    interfaces/StarEntity.cpp
    interfaces/StarFireableItem.cpp
    interfaces/StarInteractiveEntity.cpp
    interfaces/StarLoungingEntities.cpp
    interfaces/StarPhysicsEntity.cpp
    interfaces/StarPointableItem.cpp
    interfaces/StarSwingableItem.cpp
    interfaces/StarTileEntity.cpp
    interfaces/StarToolUserItem.cpp
    interfaces/StarWorld.cpp

    items/StarArmors.cpp
    items/StarAugmentItem.cpp
    items/StarTools.cpp

    objects/StarContainerObject.cpp

    scripting/StarLuaComponents.cpp
    scripting/StarLuaEntityUserdata.cpp
    scripting/StarLuaGameConverters.cpp
    scripting/StarLuaRoot.cpp
    scripting/StarScriptableThread.cpp
  )

add_library (star_game_module_interfaces OBJECT)
target_sources (star_game_module_interfaces PUBLIC FILE_SET CXX_MODULES FILES
    scripting/StarEntityLuaBindings.cppm
    scripting/StarMovementControllerLuaBindings.cppm
    scripting/StarWorldLuaBindings.cppm
    scripting/StarLuaHttpBindings.cppm
    scripting/StarPlayerLuaBindings.cppm
    scripting/StarRootLuaBindings.cppm
    scripting/StarItemLuaBindings.cppm
    scripting/StarStatusControllerLuaBindings.cppm
    scripting/StarFireableItemLuaBindings.cppm
    scripting/StarNetworkedAnimatorLuaBindings.cppm
    scripting/StarCelestialLuaBindings.cppm
    scripting/StarUniverseServerLuaBindings.cppm
    scripting/StarCameraLuaBindings.cppm
    scripting/StarInputLuaBindings.cppm
    scripting/StarTeamClientLuaBindings.cppm
    scripting/StarSongbookLuaBindings.cppm
    scripting/StarBehaviorLuaBindings.cppm
    scripting/StarUniverseClientLuaBindings.cppm
    scripting/StarScriptedAnimatorLuaBindings.cppm
    scripting/StarConfigLuaBindings.cppm
    terrain/StarBasicSelectors.cppm
    terrain/StarCompositionSelectors.cppm
    terrain/StarTransformSelectors.cppm
    terrain/StarPerlinSelector.cppm
    terrain/StarIslandSurfaceSelector.cppm
    terrain/StarRidgeBlocksSelector.cppm
    terrain/StarKarstCave.cppm
    terrain/StarWormCave.cppm
    terrain/StarCacheSelector.cppm
    objects/StarTeleporterObject.cppm
    objects/StarPhysicsObject.cppm
    objects/StarLoungeableObject.cppm
    objects/StarFarmableObject.cppm
    items/StarThrownItem.cppm
    items/StarUnlockItem.cppm
    items/StarBlueprintItem.cppm
    items/StarCodexItem.cppm
    items/StarCurrency.cppm
    items/StarConsumableItem.cppm
    items/StarInspectionTool.cppm
    items/StarInstrumentItem.cppm
    items/StarLiquidItem.cppm
    items/StarMaterialItem.cppm
    items/StarActiveItem.cppm
    items/StarFlashlight.cppm
    items/StarTillingTool.cppm
    items/StarObjectItem.cppm
    StarDungeonImagePart.cppm
    StarDungeonTMXPart.cppm
    StarMicroDungeon.cppm
    StarWorldGeneration.cppm
    StarDanceDatabase.cppm
    StarTechDatabase.cppm
    StarCodexDatabase.cppm
    StarCollectionDatabase.cppm
    StarStagehandDatabase.cppm
    StarEmoteProcessor.cppm
    StarDamageDatabase.cppm
    StarEffectSourceDatabase.cppm
    StarParticleDatabase.cppm
    StarRadioMessageDatabase.cppm
    StarStatusEffectDatabase.cppm
    StarQuestTemplateDatabase.cppm
    StarSpawnTypeDatabase.cppm
    StarTenantDatabase.cppm
    StarStatisticsDatabase.cppm
    StarVersioningDatabase.cppm
    StarLiquidsDatabase.cppm
    StarTerrainDatabase.cppm
    StarTilesetDatabase.cppm
    StarBehaviorDatabase.cppm
    StarAiDatabase.cppm
    StarSpeciesDatabase.cppm
    StarVehicleDatabase.cppm
    StarProjectileDatabase.cppm
    StarPlantDatabase.cppm
    StarNpcDatabase.cppm
    StarObjectDatabase.cppm
    StarItemDatabase.cppm
    StarMaterialDatabase.cppm
    StarMonsterDatabase.cppm
    StarCelestialDatabase.cppm
    StarImageMetadataDatabase.cppm
    StarBiomeDatabase.cppm
    StarStoredFunctions.cppm
    StarTreasure.cppm
    StarNameGenerator.cppm
    StarRebuilder.cppm
    StarStatSet.cppm
    StarStatCollection.cppm
    StarAnimation.cppm
    StarAmbient.cppm
  )
target_include_directories (star_game_module_interfaces PRIVATE
    ${STAR_EXTERN_INCLUDES}
    ${STAR_CORE_INCLUDES}
    ${STAR_BASE_INCLUDES}
    ${STAR_PLATFORM_INCLUDES}
    ${STAR_GAME_INCLUDES}
  )
target_link_libraries (star_game_module_interfaces PRIVATE star_modules star_build_config)

# Keep implementation template instantiations out of interface BMIs.
add_library (star_game_modules STATIC
    StarStoredFunctions.cpp
    StarTreasure.cpp
    StarNameGenerator.cpp
    StarRebuilder.cpp
    StarStatSet.cpp
    StarStatCollection.cpp
    StarAnimation.cpp
    StarAmbient.cpp
    scripting/StarCameraLuaBindings.cpp
    scripting/StarEntityLuaBindings.cpp
    scripting/StarItemLuaBindings.cpp
    scripting/StarPlayerLuaBindings.cpp
    scripting/StarMovementControllerLuaBindings.cpp
    scripting/StarWorldLuaBindings.cpp
    scripting/StarStatusControllerLuaBindings.cpp
    scripting/StarCelestialLuaBindings.cpp
    scripting/StarLuaHttpBindings.cpp
    scripting/StarUniverseClientLuaBindings.cpp
    scripting/StarUniverseServerLuaBindings.cpp
    scripting/StarTeamClientLuaBindings.cpp
    scripting/StarInputLuaBindings.cpp
    scripting/StarConfigLuaBindings.cpp
    StarWorldGeneration.cpp
    StarMicroDungeon.cpp
    objects/StarFarmableObject.cpp
    objects/StarLoungeableObject.cpp
    objects/StarPhysicsObject.cpp
    scripting/StarRootLuaBindings.cpp
    scripting/StarBehaviorLuaBindings.cpp
    StarDungeonTMXPart.cpp
    StarDanceDatabase.cpp
    StarTechDatabase.cpp
    StarCodexDatabase.cpp
    StarCollectionDatabase.cpp
    StarStagehandDatabase.cpp
    StarEmoteProcessor.cpp
    StarDamageDatabase.cpp
    StarEffectSourceDatabase.cpp
    StarParticleDatabase.cpp
    StarRadioMessageDatabase.cpp
    StarStatusEffectDatabase.cpp
    StarQuestTemplateDatabase.cpp
    StarSpawnTypeDatabase.cpp
    StarTenantDatabase.cpp
    StarStatisticsDatabase.cpp
    StarVersioningDatabase.cpp
    StarLiquidsDatabase.cpp
    StarTerrainDatabase.cpp
    StarTilesetDatabase.cpp
    StarBehaviorDatabase.cpp
    StarAiDatabase.cpp
    StarSpeciesDatabase.cpp
    StarVehicleDatabase.cpp
    StarProjectileDatabase.cpp
    StarPlantDatabase.cpp
    StarNpcDatabase.cpp
    StarObjectDatabase.cpp
    StarItemDatabase.cpp
    StarMaterialDatabase.cpp
    StarMonsterDatabase.cpp
    StarCelestialDatabase.cpp
    StarImageMetadataDatabase.cpp
    StarBiomeDatabase.cpp
  )
target_include_directories (star_game_modules PRIVATE
    ${STAR_EXTERN_INCLUDES}
    ${STAR_CORE_INCLUDES}
    ${STAR_BASE_INCLUDES}
    ${STAR_PLATFORM_INCLUDES}
    ${STAR_GAME_INCLUDES}
  )
target_link_libraries (star_game_modules PUBLIC star_game_module_interfaces PRIVATE star_modules star_build_config)
set_target_properties (star_game_modules PROPERTIES CXX_SCAN_FOR_MODULES ON)

add_library (star_game OBJECT ${star_game_SOURCES} ${star_game_HEADERS})
target_include_directories (star_game PRIVATE
    ${STAR_EXTERN_INCLUDES}
    ${STAR_CORE_INCLUDES}
    ${STAR_BASE_INCLUDES}
    ${STAR_PLATFORM_INCLUDES}
    ${STAR_GAME_INCLUDES}
  )

# See the note in base/CMakeLists.txt: star_game imports a module too.
target_link_libraries (star_game PRIVATE star_base_modules star_game_modules star_build_config)
set_target_properties (star_game PROPERTIES CXX_SCAN_FOR_MODULES ON)

if(STAR_PRECOMPILED_HEADERS)
  target_precompile_headers (star_game REUSE_FROM star_core)
endif()

if(DEFINED STAR_MSVC_RUNTIME_LIBRARY)
  set_target_properties (star_game_module_interfaces star_game_modules star_game PROPERTIES MSVC_RUNTIME_LIBRARY "${STAR_MSVC_RUNTIME_LIBRARY}")
endif()
