# Some ARM64 vcpkg-make ports stage under DESTDIR/usr/local or DESTDIR/usr.
# Move their full installation trees before pkg-config validation and CMake imports.
foreach(config IN ITEMS "" "/debug")
    set(package_dir "${CURRENT_PACKAGES_DIR}${config}")
    foreach(prefix IN ITEMS "usr/local" "usr")
        set(staging_dir "${package_dir}/${prefix}")
        if(IS_DIRECTORY "${staging_dir}")
            file(GLOB_RECURSE staged_files LIST_DIRECTORIES FALSE RELATIVE "${staging_dir}" "${staging_dir}/*")
            foreach(relative_path IN LISTS staged_files)
                set(destination "${package_dir}/${relative_path}")
                if(EXISTS "${destination}" OR IS_SYMLINK "${destination}")
                    message(FATAL_ERROR "${PORT} staged file collides with ${destination}")
                endif()
                get_filename_component(destination_dir "${destination}" DIRECTORY)
                file(MAKE_DIRECTORY "${destination_dir}")
                file(RENAME "${staging_dir}/${relative_path}" "${destination}")
            endforeach()
            file(REMOVE_RECURSE "${staging_dir}")
        endif()
    endforeach()
endforeach()
