add_library (star_frontend_module_interfaces OBJECT)
target_sources (star_frontend_module_interfaces PUBLIC FILE_SET CXX_MODULES FILES
    StarSimpleTooltip.cppm
    StarHttpTrustDialog.cppm
    StarItemTooltip.cppm
    StarClipboardLuaBindings.cppm
    StarVoiceLuaBindings.cppm
    StarInterfaceLuaBindings.cppm
    StarBindingsMenu.cppm
    StarBookmarkInterface.cppm
    StarConfirmationDialog.cppm
    StarErrorScreen.cppm
    StarGraphicsMenu.cppm
    StarJoinRequestDialog.cppm
    StarKeybindingsMenu.cppm
    StarModsMenu.cppm
    StarOptionsMenu.cppm
    StarPopupInterface.cppm
    StarRadioMessagePopup.cppm
    StarShadersMenu.cppm
    StarTeleportDialog.cppm
    StarVoiceSettingsMenu.cppm
    StarCharCreation.cppm
    StarCharSelection.cppm
    StarCodexInterface.cppm
    StarQuestInterface.cppm
    StarSongbookInterface.cppm
    StarAiInterface.cppm
    StarActionBar.cppm
    StarBaseScriptPane.cppm
    StarChat.cppm
    StarChatBubbleSeparation.cppm
    StarChatBubbleManager.cppm
    StarContainerInterface.cppm
    StarContainerInteractor.cppm
    StarCraftingInterface.cppm
    StarInventory.cppm
    StarInterfaceCursor.cppm
    StarMainInterfaceTypes.cppm
    StarMainMixer.cppm
    StarMerchantInterface.cppm
    StarNameplatePainter.cppm
    StarQuestIndicatorPainter.cppm
    StarQuestTracker.cppm
    StarScriptPane.cppm
    StarStatusPane.cppm
    StarTeamBar.cppm
    StarWireInterface.cppm
    StarCinematic.cppm
    StarClientCommandProcessor.cppm
    StarMainInterface.cppm
    StarTitleScreen.cppm
    StarVoice.cppm
  )
target_include_directories (star_frontend_module_interfaces PRIVATE
    ${STAR_EXTERN_INCLUDES}
    ${STAR_CORE_INCLUDES}
    ${STAR_BASE_INCLUDES}
    ${STAR_GAME_INCLUDES}
    ${STAR_PLATFORM_INCLUDES}
    ${STAR_APPLICATION_INCLUDES}
    ${STAR_RENDERING_INCLUDES}
    ${STAR_WINDOWING_INCLUDES}
    ${STAR_FRONTEND_INCLUDES}
  )
target_link_libraries (star_frontend_module_interfaces PUBLIC star_game_module_interfaces star_application_module_interfaces star_rendering_module_interfaces star_windowing_module_interfaces PRIVATE star_build_config)

add_library (star_frontend_modules STATIC
    StarInterfaceLuaBindings.cpp
    StarHttpTrustDialog.cpp
    StarVoiceLuaBindings.cpp
    StarClipboardLuaBindings.cpp
    StarBindingsMenu.cpp
    StarBookmarkInterface.cpp
    StarConfirmationDialog.cpp
    StarErrorScreen.cpp
    StarGraphicsMenu.cpp
    StarJoinRequestDialog.cpp
    StarKeybindingsMenu.cpp
    StarModsMenu.cpp
    StarOptionsMenu.cpp
    StarPopupInterface.cpp
    StarRadioMessagePopup.cpp
    StarShadersMenu.cpp
    StarTeleportDialog.cpp
    StarVoiceSettingsMenu.cpp
    StarCharCreation.cpp
    StarCharSelection.cpp
    StarCodexInterface.cpp
    StarQuestInterface.cpp
    StarSongbookInterface.cpp
    StarAiInterface.cpp
    StarActionBar.cpp
    StarBaseScriptPane.cpp
    StarChat.cpp
    StarChatBubbleSeparation.cpp
    StarChatBubbleManager.cpp
    StarContainerInterface.cpp
    StarContainerInteractor.cpp
    StarCraftingInterface.cpp
    StarInventory.cpp
    StarInterfaceCursor.cpp
    StarMainInterfaceTypes.cpp
    StarMainMixer.cpp
    StarMerchantInterface.cpp
    StarNameplatePainter.cpp
    StarQuestIndicatorPainter.cpp
    StarQuestTracker.cpp
    StarScriptPane.cpp
    StarStatusPane.cpp
    StarTeamBar.cpp
    StarWireInterface.cpp
    StarCinematic.cpp
    StarClientCommandProcessor.cpp
    StarMainInterface.cpp
    StarTitleScreen.cpp
    StarVoice.cpp
  )
target_include_directories (star_frontend_modules PRIVATE
    ${STAR_EXTERN_INCLUDES}
    ${STAR_CORE_INCLUDES}
    ${STAR_BASE_INCLUDES}
    ${STAR_GAME_INCLUDES}
    ${STAR_PLATFORM_INCLUDES}
    ${STAR_APPLICATION_INCLUDES}
    ${STAR_RENDERING_INCLUDES}
    ${STAR_WINDOWING_INCLUDES}
    ${STAR_FRONTEND_INCLUDES}
  )
target_link_libraries (star_frontend_modules PUBLIC star_frontend_module_interfaces star_game_modules star_rendering_modules star_windowing_modules star_application_modules PRIVATE star_build_config star_voice_dependencies)
set_target_properties (star_frontend_modules PROPERTIES CXX_SCAN_FOR_MODULES ON)

if(DEFINED STAR_MSVC_RUNTIME_LIBRARY)
  set_target_properties (star_frontend_module_interfaces star_frontend_modules PROPERTIES MSVC_RUNTIME_LIBRARY "${STAR_MSVC_RUNTIME_LIBRARY}")
endif()
