# Add project defaults only when the caller has not selected that class of
# option. CMake's own configuration initializers are not caller overrides.
function(star_default_compile_options config kind)
  string(TOUPPER "${config}" config_upper)
  if(kind STREQUAL "optimization")
    set(override_pattern "(^|[ \t])(-O[^ \t]*|/O[^ \t]*)([ \t]|$)")
  elseif(kind STREQUAL "math")
    set(override_pattern "(^|[ \t])(-f(no-)?fast-math|/fp:[^ \t]*)([ \t]|$)")
  else()
    set(override_pattern "(^|[ \t])(-g([0-9]+|line-tables-only)?|/Z[7iI])([ \t]|$)")
  endif()
  foreach(language C CXX)
    set(flag_variable CMAKE_${language}_FLAGS_${config_upper})
    string(STRIP "${${flag_variable}}" config_flags)
    string(STRIP "${${flag_variable}_INIT}" initial_flags)
    set(caller_flags "${CMAKE_${language}_FLAGS}")
    if(STAR_EXPLICIT_${language}_FLAGS_${config_upper} OR NOT config_flags STREQUAL initial_flags)
      string(APPEND caller_flags " ${config_flags}")
    endif()
    if(NOT caller_flags MATCHES "${override_pattern}")
      foreach(option IN LISTS ARGN)
        target_compile_options(star_build_config INTERFACE
          "$<$<AND:$<COMPILE_LANGUAGE:${language}>,$<CONFIG:${config}>>:${option}>")
      endforeach()
    endif()
  endforeach()
endfunction()

target_compile_definitions(star_build_config INTERFACE
  "$<$<CONFIG:Release,RelWithDebInfo>:NDEBUG>")

if(STAR_COMPILER_GNU OR STAR_COMPILER_CLANG)
  target_compile_options(star_build_config INTERFACE
    "$<$<COMPILE_LANGUAGE:C,CXX>:-Wall;-Wextra>")
  if(STAR_COMPILER_GNU)
    target_compile_options(star_build_config INTERFACE
      "$<$<COMPILE_LANGUAGE:C,CXX>:-Wno-unused;-Wno-implicit-fallthrough>")
    target_link_options(star_build_config INTERFACE -rdynamic -no-pie)
    if(STAR_SYSTEM_FAMILY_WINDOWS)
      target_compile_options(star_build_config INTERFACE "$<$<COMPILE_LANGUAGE:C,CXX>:-mthreads>")
      target_link_options(star_build_config INTERFACE -mthreads)
    endif()
    if(STAR_ENABLE_STATIC_LIBGCC_LIBSTDCXX)
      target_link_options(star_build_config INTERFACE -static-libgcc "$<$<LINK_LANGUAGE:CXX>:-static-libstdc++>")
    endif()
    if(STAR_ENABLE_GCC_PROFILING)
      target_compile_options(star_build_config INTERFACE "$<$<COMPILE_LANGUAGE:C,CXX>:-pg>")
      target_link_options(star_build_config INTERFACE -pg)
    endif()
    if(STAR_ENABLE_GLIBCXX_DEBUG)
      target_compile_definitions(star_build_config INTERFACE _GLIBCXX_DEBUG)
    endif()
    star_default_compile_options(Debug optimization -Og)
  else()
    target_compile_options(star_build_config INTERFACE
      "$<$<COMPILE_LANGUAGE:C,CXX>:-Wuninitialized;-Wno-parentheses-equality;-Wno-deprecated-declarations;-Wno-nan-infinity-disabled>")
    if(STAR_SYSTEM_MACOS)
      target_compile_options(star_build_config INTERFACE "$<$<COMPILE_LANGUAGE:CXX>:-stdlib=libc++>")
      target_link_options(star_build_config INTERFACE "$<$<LINK_LANGUAGE:CXX>:-stdlib=libc++>" "LINKER:-export_dynamic")
    elseif(NOT STAR_SYSTEM_WINDOWS)
      target_link_options(star_build_config INTERFACE "LINKER:--export-dynamic")
    endif()
  endif()

  if(NOT STAR_SYSTEM_WINDOWS AND (STAR_COMPILER_GNU OR NOT STAR_SYSTEM_MACOS))
    target_compile_options(star_build_config INTERFACE "$<$<COMPILE_LANGUAGE:C,CXX>:-pthread>")
    target_compile_definitions(star_build_config INTERFACE _REENTRANT)
    target_link_options(star_build_config INTERFACE -pthread)
  endif()

  foreach(config RelWithAsserts RelWithDebInfo Release)
    star_default_compile_options(${config} optimization -O3)
    star_default_compile_options(${config} math -ffast-math)
  endforeach()

  foreach(config Debug RelWithAsserts RelWithDebInfo)
    if(STAR_DEBUG_SYMBOL_LEVEL STREQUAL "minimal")
      if(STAR_COMPILER_CLANG)
        set(debug_option -gline-tables-only)
      else()
        set(debug_option -g1)
      endif()
    elseif(STAR_DEBUG_SYMBOL_LEVEL STREQUAL "default" AND STAR_COMPILER_CLANG AND config STREQUAL "RelWithDebInfo")
      set(debug_option -gline-tables-only)
    else()
      set(debug_option -g)
    endif()
    star_default_compile_options(${config} debug ${debug_option})
  endforeach()
  if(STAR_COMPILER_CLANG)
    if(STAR_SYSTEM_WINDOWS)
      target_compile_options(star_build_config INTERFACE
        "$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<CONFIG:RelWithDebInfo>>:-gcodeview>")
    else()
      target_compile_options(star_build_config INTERFACE
        "$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<CONFIG:RelWithDebInfo>>:-gz=zlib>")
    endif()
  endif()

elseif(STAR_COMPILER_MSVC)
  target_compile_options(star_build_config INTERFACE
    "$<$<COMPILE_LANGUAGE:C,CXX>:/nologo;/MP;/bigobj;/wd4996;/wd4351;/wd4800;/wd4244;/wd4305;/wd4267;/wd4456;/wd4503;/wd4250;/wd4624>"
    "$<$<COMPILE_LANGUAGE:CXX>:/EHsc>")
  target_compile_definitions(star_build_config INTERFACE UNICODE _UNICODE NOMINMAX)
  if(STAR_ENABLE_STATIC_MSVC_RUNTIME)
    # Child targets apply this property; it is not an INTERFACE usage requirement.
    set(STAR_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
  endif()
  star_default_compile_options(Debug optimization /Od)
  foreach(config Debug RelWithAsserts RelWithDebInfo)
    star_default_compile_options(${config} debug /Z7)
  endforeach()
  foreach(config RelWithAsserts RelWithDebInfo Release)
    star_default_compile_options(${config} optimization /Ox)
    star_default_compile_options(${config} math /fp:fast)
    target_compile_options(star_build_config INTERFACE
      "$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<CONFIG:${config}>>:/GA;/GS-;/Gy>")
    if(STAR_ARCHITECTURE_I386)
      target_compile_options(star_build_config INTERFACE
        "$<$<AND:$<COMPILE_LANGUAGE:C,CXX>,$<CONFIG:${config}>>:/arch:SSE2>")
    endif()
  endforeach()
  target_link_options(star_build_config INTERFACE /largeaddressaware /OPT:REF /OPT:ICF /PDBCompress
    "$<$<CONFIG:RelWithAsserts>:/DEBUG>")

else()
  target_compile_options(star_build_config INTERFACE "$<$<COMPILE_LANGUAGE:C,CXX>:-Wall;-pthread>")
  target_compile_definitions(star_build_config INTERFACE _REENTRANT)
  target_link_options(star_build_config INTERFACE -pthread)
  foreach(config Debug RelWithAsserts RelWithDebInfo)
    if(STAR_DEBUG_SYMBOL_LEVEL STREQUAL "minimal")
      star_default_compile_options(${config} debug -g1)
    else()
      star_default_compile_options(${config} debug -g)
    endif()
  endforeach()
  foreach(config RelWithAsserts RelWithDebInfo Release)
    star_default_compile_options(${config} optimization -O2)
  endforeach()
endif()

if(STAR_SYSTEM_MACOS)
  target_link_options(star_build_config INTERFACE
    "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:-flat_namespace;-undefined;suppress>")
endif()
