# vcpkg validates .pc files and imports libraries from the package root, not usr/.
foreach(config IN ITEMS "" "/debug")
    set(package_dir "${CURRENT_PACKAGES_DIR}${config}")
    set(usr_dir "${package_dir}/usr")
    if(EXISTS "${usr_dir}")
        file(GLOB_RECURSE usr_files LIST_DIRECTORIES FALSE RELATIVE "${usr_dir}" "${usr_dir}/*")
        foreach(relative_path IN LISTS usr_files)
            set(destination "${package_dir}/${relative_path}")
            if(EXISTS "${destination}")
                message(FATAL_ERROR "ALSA staged file collides with ${destination}")
            endif()
            get_filename_component(destination_dir "${destination}" DIRECTORY)
            file(MAKE_DIRECTORY "${destination_dir}")
            file(RENAME "${usr_dir}/${relative_path}" "${destination}")
        endforeach()
        file(REMOVE_RECURSE "${usr_dir}")
    endif()
endforeach()
